###===  文件上传处理   =====##
file:
  upload:
    method: local
    store:
      path: D:/nginx-1.2.8/html/
    access:
      domain: http://127.0.0.1

#==== db config =======#
spring:
  datasource:
    master:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://139.196.83.11:3306/new_portal?useUnicode=true&characterEncoding=utf-8
      username: xqsight
      password: password
      initialSize: 10
      maxActive: 20
      maxIdle: 5
      minIdle: 1
      maxWait: 10000
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
      removeAbandoned: true
      removeAbandonedTimeout: 60000
      logAbandoned: true
      #druid:
      #  connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAPR3s42h+p61h9xNaG4KcPmi6P5WrR/PUvDYHI8Elr0q8OOqZH5FuC7mldD56+cWh45UhENK1ZrGo8zoczeBOP0CAwEAAQ==
    slave:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://139.196.83.11:3306/new_portal?useUnicode=true&characterEncoding=utf-8
      username: xqsight
      password: password
      initialSize: 10
      maxActive: 20
      maxIdle: 5
      minIdle: 1
      maxWait: 10000
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
      removeAbandoned: true
      removeAbandonedTimeout: 60000
      logAbandoned: true
      #druid:
      #  connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAPR3s42h+p61h9xNaG4KcPmi6P5WrR/PUvDYHI8Elr0q8OOqZH5FuC7mldD56+cWh45UhENK1ZrGo8zoczeBOP0CAwEAAQ==
