# tomcat config
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080


spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
